; Offset ASCII - 0x20, also replace # with ©, and other miscellaneous characters.
; This might be subject to change -- in the released English patch, level names and bonus text already use regular ASCII
charmap " ", $00
charmap "!", $01
charmap """, $02
charmap "©", $03
charmap "$", $04
charmap "%", $05
charmap "&", $06
charmap "'", $07
charmap "(", $08
charmap ")", $09
charmap "*", $0A
charmap "+", $0B
charmap ",", $0C
charmap "-", $0D
charmap ".", $0E
charmap "/", $0F
charmap "0", $10
charmap "1", $11
charmap "2", $12
charmap "3", $13
charmap "4", $14
charmap "5", $15
charmap "6", $16
charmap "7", $17
charmap "8", $18
charmap "9", $19
charmap ":", $1A
charmap ";", $1B
charmap "<", $1C
charmap "=", $1D
charmap ">", $1E
charmap "?", $1F
charmap "@", $20
charmap "A", $21
charmap "B", $22
charmap "C", $23
charmap "D", $24
charmap "E", $25
charmap "F", $26
charmap "G", $27
charmap "H", $28
charmap "I", $29
charmap "J", $2A
charmap "K", $2B
charmap "L", $2C
charmap "M", $2D
charmap "N", $2E
charmap "O", $2F
charmap "P", $30
charmap "Q", $31
charmap "R", $32
charmap "S", $33
charmap "T", $34
charmap "U", $35
charmap "V", $36
charmap "W", $37
charmap "X", $38
charmap "Y", $39
charmap "Z", $3A
charmap "™", $3B
charmap "ä", $3C
charmap "ö", $3D
charmap "ü", $3E
charmap "ß", $3F
charmap "ç", $40
charmap "a", $41
charmap "b", $42
charmap "c", $43
charmap "d", $44
charmap "e", $45
charmap "f", $46
charmap "g", $47
charmap "h", $48
charmap "i", $49
charmap "j", $4A
charmap "k", $4B
charmap "l", $4C
charmap "m", $4D
charmap "n", $4E
charmap "o", $4F
charmap "p", $50
charmap "q", $51
charmap "r", $52
charmap "s", $53
charmap "t", $54
charmap "u", $55
charmap "v", $56
charmap "w", $57
charmap "x", $58
charmap "y", $59
charmap "z", $5A
charmap "á", $5B
charmap "à", $5C
charmap "â", $5D
charmap "é", $5E
charmap "è", $5F
charmap "ê", $60
charmap "í", $61
charmap "ì", $62
charmap "ï", $63
charmap "î", $64
charmap "ó", $65
charmap "ò", $66
charmap "ô", $67
charmap "ú", $68
charmap "ù", $69
charmap "û", $6A
charmap "Ú", $6B
charmap "ñ", $6C
charmap "À", $6D
charmap "È", $6E
charmap "Ì", $6F
charmap "Ó", $70
charmap "Ú", $71
charmap "Ñ", $72
charmap "¡", $73
charmap "¿", $74
charmap "←", $75
charmap "→", $76
charmap "↑", $77
charmap "↓", $78
charmap "Ｄ", $79
charmap "Ｇ", $7A
charmap "Ｈ", $7B
charmap "Ｋ", $7C
charmap "Ｏ", $7D
charmap "Ｒ", $7E
charmap "Ｓ", $7F
charmap "Ｕ", $80
charmap "!", $81
charmap "?", $82
charmap "ザ", $83
charmap "、", $84
charmap "上", $85
charmap "下", $86
charmap "左", $87
charmap "右", $88
charmap "行", $89
charmap "店", $8A
charmap "赤", $8B
charmap "海", $8C
charmap "辺", $8D
charmap "相", $8E
charmap "丢", $8F
charmap "命", $90
charmap "水", $91
charmap "川", $92
charmap "大", $93
charmap "穴", $94
charmap "足", $95
charmap "元", $96
charmap "子", $97
charmap "石", $98
charmap "雨", $99
charmap "山", $9A
charmap "森", $9B
charmap "台", $9C
charmap "北", $9D
charmap "失", $9E
charmap "生", $9F
charmap "活", $A0
charmap "湖", $A1
charmap "音", $A2
charmap "向", $A3
charmap "文", $A4
charmap "字", $A5
charmap "目", $A6
charmap "先", $A7
charmap "友", $A8
charmap "役", $A9
charmap "立", $AA
charmap "的", $AB
charmap "毛", $AC
charmap "全", $AD
charmap "部", $AE
charmap "信", $AF
; charmap "?", $B0
charmap "竹", $B1
charmap "木", $B2
; charmap "?", $B3
charmap "茶", $B4
charmap "来", $B5
charmap "時", $B6
charmap "計", $B7
charmap "力", $B8
charmap "打", $B9
charmap "気", $BA
charmap "何", $BB
charmap "秒", $BC
charmap "オ", $BD
charmap "入", $BE
charmap "力", $BF
charmap "０", $C0
charmap "１", $C1
charmap "２", $C2
charmap "３", $C3
charmap "４", $C4
charmap "５", $C5
charmap "６", $C6
charmap "７", $C7
charmap "８", $C8
charmap "９", $C9
charmap "が", $CA
charmap "ぎ", $CB
charmap "ぱ", $CC
charmap "ぷ", $CD
charmap "モ", $CE
charmap " ", $CF
charmap "ニ", $D0
charmap "エ", $D1
; charmap "\n", $FF