charmap "あ", $00
charmap "い", $01
charmap "う", $02
charmap "え", $03
charmap "お", $04
charmap "か", $05
charmap "き", $06
charmap "く", $07
charmap "け", $08
charmap "こ", $09
charmap "さ", $0A
charmap "し", $0B
charmap "す", $0C
charmap "せ", $0D
charmap "そ", $0E
charmap "た", $0F
charmap "ち", $10
charmap "つ", $11
charmap "て", $12
charmap "と", $13
charmap "な", $14
charmap "に", $15
charmap "ね", $16
charmap "の", $17
charmap "は", $18
charmap "ひ", $19
charmap "ふ", $1A
charmap "へ", $1B
charmap "ほ", $1C
charmap "ま", $1D
charmap "み", $1E
charmap "む", $1F
charmap "め", $20
charmap "も", $21
charmap "や", $22
charmap "ゆ", $23
charmap "よ", $24
charmap "ら", $25
charmap "り", $26
charmap "る", $27
charmap "れ", $28
charmap "ろ", $29
charmap "わ", $2A
charmap "を", $2B
charmap "ん", $2C
charmap "が", $2D
charmap "ぎ", $2E
charmap "ぐ", $2F
charmap "げ", $30
charmap "ご", $31
charmap "ざ", $32
charmap "じ", $33
charmap "ず", $34
charmap "ぜ", $35
charmap "ぞ", $36
charmap "だ", $37
charmap "で", $38
charmap "ど", $39
charmap "ば", $3A
charmap "び", $3B
charmap "ぶ", $3C
charmap "べ", $3D
charmap "ぼ", $3E
charmap "っ", $3F
charmap "ゃ", $40
charmap "ゅ", $41
charmap "ょ", $42
charmap "ア", $43
charmap "イ", $44
charmap "ウ", $45
charmap "カ", $46
charmap "キ", $47
charmap "ク", $48
charmap "ケ", $49
charmap "コ", $4A
charmap "サ", $4B
charmap "シ", $4C
charmap "ス", $4D
charmap "セ", $4E
charmap "タ", $4F
charmap "チ", $50
charmap "ツ", $51
charmap "テ", $52
charmap "ト", $53
charmap "ナ", $54
charmap "ノ", $55
charmap "フ", $56
charmap "マ", $57
charmap "ミ", $58
charmap "ム", $59
charmap "ラ", $5A
charmap "リ", $5B
charmap "ル", $5C
charmap "レ", $5D
charmap "ロ", $5E
charmap "ワ", $5F
charmap "ン", $60
charmap "グ", $61
charmap "ゲ", $62
charmap "ゴ", $63
charmap "ジ", $64
charmap "ズ", $65
charmap "ダ", $66
charmap "デ", $67
charmap "ド", $68
charmap "バ", $69
charmap "ビ", $6A
charmap "ブ", $6B
charmap "ボ", $6C
charmap "プ", $6D
charmap "ペ", $6E
charmap "ポ", $6F
charmap "ァ", $70
charmap "ィ", $71
charmap "ォ", $72
charmap "ッ", $73
charmap "ャ", $74
charmap "ュ", $75
charmap "ー", $76
charmap "〜", $77
charmap "A", $78
charmap "D", $79
charmap "G", $7A
charmap "H", $7B
charmap "K", $7C
charmap "O", $7D
charmap "R", $7E
charmap "S", $7F
charmap "U", $80
charmap "!", $81
charmap "?", $82
charmap "ザ", $83
charmap "、", $84
charmap "上", $85
charmap "下", $86
charmap "左", $87
charmap "右", $88
charmap "行", $89
charmap "店", $8A
charmap "赤", $8B
charmap "海", $8C
charmap "辺", $8D
charmap "相", $8E
charmap "丢", $8F
charmap "命", $90
charmap "水", $91
charmap "川", $92
charmap "大", $93
charmap "穴", $94
charmap "足", $95
charmap "元", $96
charmap "子", $97
charmap "石", $98
charmap "雨", $99
charmap "山", $9A
charmap "森", $9B
charmap "台", $9C
charmap "北", $9D
charmap "失", $9E
charmap "生", $9F
charmap "活", $A0
charmap "湖", $A1
charmap "音", $A2
charmap "向", $A3
charmap "文", $A4
charmap "字", $A5
charmap "目", $A6
charmap "先", $A7
charmap "友", $A8
charmap "役", $A9
charmap "立", $AA
charmap "的", $AB
charmap "毛", $AC
charmap "全", $AD
charmap "部", $AE
charmap "信", $AF
; charmap "?", $B0
charmap "竹", $B1
charmap "木", $B2
; charmap "?", $B3
charmap "茶", $B4
charmap "来", $B5
charmap "時", $B6
charmap "計", $B7
charmap "力", $B8
charmap "打", $B9
charmap "気", $BA
charmap "何", $BB
charmap "秒", $BC
charmap "オ", $BD
charmap "入", $BE
charmap "力", $BF
charmap "0", $C0
charmap "1", $C1
charmap "2", $C2
charmap "3", $C3
charmap "4", $C4
charmap "5", $C5
charmap "6", $C6
charmap "7", $C7
charmap "8", $C8
charmap "9", $C9
charmap "が", $CA
charmap "ぎ", $CB
charmap "ぱ", $CC
charmap "ぷ", $CD
charmap "モ", $CE
charmap " ", $CF
charmap "ニ", $D0
charmap "エ", $D1
; charmap "\n", $FF