.PHONY: all clean compare_roms

BASE_DIR := baserom
BUILD_DIR := build

# Build DKL3
ROM := ${BUILD_DIR}/dkl3_jp.gbc
BASEROM = ${BASE_DIR}/dkl3_jp.gbc
OBJS := $(patsubst %.asm,%.o,$(shell find game/src -type f -name "*.asm")) # Fix this	

TILEMAP_CSV := gfx/tilemaps/title_tmap.csv
TILEMAP_BIN := $(BUILD_DIR)/gfx/tilemaps/title_tmap.bin

# Link objects together to build a rom.
all: $(ROM) compare_roms

# Assemble source files into objects.
# Use rgbasm -h to use halts without nops.
$(OBJS:%.o=${BUILD_DIR}/%.o): $(BUILD_DIR)/%.o : %.asm
	@echo "Assembling" $<
	@mkdir -p $(dir $@)
	@rgbasm -h -o $@ $<

# $(ROM): $(OBJS:%.o=${BUILD_DIR}/%.o) $(OBJS:%.o=${BUILD_DIR}/%.o)
# 	rgblink -n $(ROM:.gbc=.sym) -m $(ROM:.gbc=.map) -O $(BASEROM) -o $@ $^  # Uses -O (overlay) to patch the retail ROM
$(ROM): $(OBJS:%.o=${BUILD_DIR}/%.o) $(BPP_FILES)
	rgblink -n $(ROM:.gbc=.sym) -m $(ROM:.gbc=.map) -O $(BASEROM) -o $@ $(filter %.o, $^)
	rgbfix -v -C -k 01 -l 0x33 -m 0x1B -p 0 -n 0 -r 2 -t "DONKEY KONG" -i "AD3J" $@
	@echo $(ROM)
	
# The compare target is a shortcut to check that the build matches the original roms exactly.
# This is for contributors to make sure a change didn't affect the contents of the rom.
# More thorough comparison can be made by diffing the output of hexdump -C against both roms.
compare_roms: $(ROM) $(BASEROM)
	cmp $^

TILEMAP_BINS := $(TILEMAP_BIN)
# Remove files generated by the build process.
clean:
	@echo $(ROM)
	rm -f $(ROM) $(OBJS) $(BPP_FILES) $(TILEMAP_BINS)

PNG_FILES := $(shell find gfx -type f -name "*.png")
BPP_FILES := $(patsubst gfx/%, $(BUILD_DIR)/gfx/%, $(PNG_FILES:.png=.2bpp))

# Paths
TITLE_TMAP := gfx/tilemaps/title_tmap.csv
TITLE_TMAP_BIN := build/gfx/tilemaps/title_tmap.bin

# ROM depends on tilemaps
build/dkl3_jp.gbc: $(TITLE_TMAP_BIN)

# Build tilemap bin from CSV
$(TITLE_TMAP_BIN): $(TITLE_TMAP) tools/build_tilemap.py
	@mkdir -p $(dir $@)
	python3 tools/build_tilemap.py $< > $@

$(BUILD_DIR)/gfx/%.2bpp: gfx/%.png
	@echo "Converting" $< "to tile data"
	@mkdir -p $(dir $@)
	rgbgfx -o $@ $<

$(ROM): $(OBJS:%.o=${BUILD_DIR}/%.o) $(BPP_FILES)
$(ROM): $(TILEMAP_BIN)